#!/usr/bin/env python
# -*- coding: utf-8 -*-

# Set up flash card sets in $HOME/.flashcards/filename
# where each filename defines an array called cards, like this:
# cards = [
#     [ "1", "one" ],
#     [ "2", "two" ],
# ]
# It will look for .flashcards/all as a default, or you can pass
# the filename as an argument, e.g. flashcard shortlist will
# use the cards defined in $HOME/.flashcard/shortlist.
#
# Copyright 2007 by Akkana Peck.
# This program is free software -- please share it under the terms
# of the GNU Public License.

import os, sys, random

def print_card(card) :
    for word in card :
        print word, "      ",
    print ""

print "Flash card script version 0.3 by Akkana Peck. (Modified by Yoshi)\n"
print "On seeing a word, think of the answer then hit return."
print "Then hit return again to see the next word."
print "But if you got it wrong, type anything besides q before hitting Return"
print "and the word will be added back to the list."
print "q<Return> quits."
print ""


if len(sys.argv) > 1 :
    cardset = sys.argv[1]
    print "Using cards from set '" + cardset + "'"
else :
    #entering lesson number
    l = raw_input("Please enter lesson number (1-12): " )
    #concatenation
    cardset = "lesson"+l

cardfile = os.path.join(os.path.expanduser("~"), ".flashcards/lesson_files", cardset)
if (os.path.exists(cardfile)) :
    execfile(cardfile)
    #print "IF success"
else :
    cardfile = os.path.join(os.path.expanduser("~"), "flashcards/lesson_files", cardset)
    if (os.path.exists(cardfile)) :
        execfile(cardfile)
    #print "ELSE success"
    #print cardfile
                      
if len(cards) > 0 :
    print "Reading", len(cards), "cards from", cardfile

print ""

#bonus_words = len(cards)
bonus = ['']

version = """
Please select your version:
(1) = Kana
(2) = English
(3) = Kanji
(4) = Kana & English
(5) = Kanji, Kana, & English
\n:"""

jon = raw_input(version)

while True :
    random.shuffle(cards)
    if len(cards) == 0:
        break

    card = cards.pop()
    if jon == '1':#Kana
        which = card[0]
    elif jon == '2':#English
        which = card[1]
    elif jon == '3':#Kanji
        which = card[2]
    elif jon == '4':#Kana&English
        which = random.choice(card[:2])
    elif jon == '5':#All Three
        which = random.choice(card)
    else:
        print 'erRror.!..'
        break

    if which == '':
        which = card[0]
    
    print which,
    if raw_input() == "q" :
        break
    print_card(card)

    ans = raw_input()
    if ans == "q" :
        break
    if ans == "m" :
        # Save another copy of this word in the list
        cards.append(card)
        bonus.append(card)
    if ans == "" :
        cards.append(card)

# Print the ones missed
print "\nMissed:"
#for card in cards[bonus_words:] :
#    print_card(card)
for card in bonus:
    print_card(card)
print ""
